<a href="https://colab.research.google.com/github/Rnaini/Quiz-2/blob/main/Q1b_NaiveBayes_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import io
import pandas as pd 
import numpy as np
from scipy.io import arff
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [6]:
# Data cache
df = pd.read_csv("/content/dataset_31_credit-g-preprocessed.csv") 
print(df)

     checking_status=<0  checking_status=0<=X<200  ...  foreign_worker=no  class
0                     1                         0  ...                  0      1
1                     0                         1  ...                  0      0
2                     0                         0  ...                  0      1
3                     1                         0  ...                  0      1
4                     1                         0  ...                  0      0
..                  ...                       ...  ...                ...    ...
995                   0                         0  ...                  0      1
996                   1                         0  ...                  0      1
997                   0                         0  ...                  0      1
998                   1                         0  ...                  0      0
999                   0                         1  ...                  0      1

[1000 rows x 62 columns]


In [7]:
print(df.shape)

(1000, 62)


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 62 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   checking_status=<0                               1000 non-null   int64
 1   checking_status=0<=X<200                         1000 non-null   int64
 2   checking_status=>=200                            1000 non-null   int64
 3   'checking_status=no checking'                    1000 non-null   int64
 4   duration                                         1000 non-null   int64
 5   'credit_history=no credits/all paid'             1000 non-null   int64
 6   'credit_history=all paid'                        1000 non-null   int64
 7   'credit_history=existing paid'                   1000 non-null   int64
 8   'credit_history=delayed previously'              1000 non-null   int64
 9   'credit_history=critical/other existing credit'  1000

In [9]:
#vairiable Independent
x = df.drop(["class"],axis=1)
#Variable dependent
y = df["class"]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.5)

In [11]:
print(x_test)

     checking_status=<0  ...  foreign_worker=no
142                   1  ...                  0
796                   1  ...                  0
858                   1  ...                  0
391                   0  ...                  0
737                   1  ...                  0
..                  ...  ...                ...
878                   1  ...                  0
826                   1  ...                  0
877                   0  ...                  0
236                   0  ...                  0
344                   0  ...                  0

[500 rows x 61 columns]


In [12]:
modelnb = GaussianNB()
nbtrain = modelnb.fit(x_test, y_train)
nbtrain.class_count_

array([159., 341.])

In [13]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,

In [14]:
np.array(y_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,

In [15]:
nbtrain.predict_proba(x_test)

array([[1.81439448e-01, 8.18560552e-01],
       [4.28305203e-02, 9.57169480e-01],
       [4.00096698e-01, 5.99903302e-01],
       [7.81977306e-01, 2.18022694e-01],
       [5.45694920e-01, 4.54305080e-01],
       [3.28524776e-03, 9.96714752e-01],
       [2.85580414e-01, 7.14419586e-01],
       [1.89030848e-01, 8.10969152e-01],
       [2.30248127e-01, 7.69751873e-01],
       [1.34628474e-01, 8.65371526e-01],
       [3.65388404e-01, 6.34611596e-01],
       [2.49855929e-01, 7.50144071e-01],
       [2.49334586e-01, 7.50665414e-01],
       [1.53050632e-01, 8.46949368e-01],
       [4.19345546e-01, 5.80654454e-01],
       [5.46039206e-01, 4.53960794e-01],
       [1.08240663e-02, 9.89175934e-01],
       [4.78502533e-07, 9.99999521e-01],
       [3.24806374e-01, 6.75193626e-01],
       [7.80034890e-01, 2.19965110e-01],
       [1.66016916e-07, 9.99999834e-01],
       [1.49751588e-01, 8.50248412e-01],
       [1.57291907e-01, 8.42708093e-01],
       [9.01219825e-01, 9.87801748e-02],
       [5.199501

In [16]:
data=[[1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1]]
ypredic = nbtrain.predict(data)
print(ypredic)

[1]


In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 39, 102],
       [114, 245]])

In [18]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.7060518731988472

In [19]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.6824512534818942

In [20]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.6940509915014164

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.568