<a href="https://colab.research.google.com/github/Rnaini/Quiz-2/blob/main/Quiz_2_1B%20NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import io
import pandas as pd 
import numpy as np
from scipy.io import arff
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [ ]:
# Data cache
df = pd.read_csv("/content/dataset_31_credit-g-preprocessed.csv") 
print(df)

     checking_status=<0  checking_status=0<=X<200  ...  foreign_worker=no  class
0                     1                         0  ...                  0      1
1                     0                         1  ...                  0      0
2                     0                         0  ...                  0      1
3                     1                         0  ...                  0      1
4                     1                         0  ...                  0      0
..                  ...                       ...  ...                ...    ...
995                   0                         0  ...                  0      1
996                   1                         0  ...                  0      1
997                   0                         0  ...                  0      1
998                   1                         0  ...                  0      0
999                   0                         1  ...                  0      1

[1000 rows x 62 columns]


In [ ]:
print(df.shape)

(1000, 62)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 62 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   checking_status=<0                               1000 non-null   int64
 1   checking_status=0<=X<200                         1000 non-null   int64
 2   checking_status=>=200                            1000 non-null   int64
 3   'checking_status=no checking'                    1000 non-null   int64
 4   duration                                         1000 non-null   int64
 5   'credit_history=no credits/all paid'             1000 non-null   int64
 6   'credit_history=all paid'                        1000 non-null   int64
 7   'credit_history=existing paid'                   1000 non-null   int64
 8   'credit_history=delayed previously'              1000 non-null   int64
 9   'credit_history=critical/other existing credit'  1000

In [ ]:
#vairiable Independent
x = df.drop(["class"],axis=1)
#Variable dependent
y = df["class"]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.5)

In [ ]:
print(x_test)

     checking_status=<0  ...  foreign_worker=no
969                   1  ...                  0
515                   1  ...                  1
669                   0  ...                  0
277                   1  ...                  0
689                   1  ...                  0
..                  ...  ...                ...
177                   1  ...                  0
562                   0  ...                  0
557                   0  ...                  0
386                   0  ...                  0
110                   0  ...                  0

[500 rows x 61 columns]


In [ ]:
modelnb = GaussianNB()
nbtrain = modelnb.fit(x_test, y_train)
nbtrain.class_count_

array([149., 351.])

In [ ]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [ ]:
np.array(y_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,

In [ ]:
nbtrain.predict_proba(x_test)

array([[1.57639044e-01, 8.42360956e-01],
       [5.24585387e-01, 4.75414613e-01],
       [9.43653230e-01, 5.63467699e-02],
       [2.03645529e-01, 7.96354471e-01],
       [2.86619306e-01, 7.13380694e-01],
       [3.13108332e-01, 6.86891668e-01],
       [2.15563967e-01, 7.84436033e-01],
       [9.99871492e-01, 1.28508024e-04],
       [4.46948320e-01, 5.53051680e-01],
       [1.03849185e-01, 8.96150815e-01],
       [3.05606188e-01, 6.94393812e-01],
       [9.99882483e-01, 1.17517062e-04],
       [7.59603940e-01, 2.40396060e-01],
       [5.94608955e-01, 4.05391045e-01],
       [3.93192119e-01, 6.06807881e-01],
       [8.18756566e-06, 9.99991812e-01],
       [7.92944248e-08, 9.99999921e-01],
       [1.42271876e-02, 9.85772812e-01],
       [7.87333300e-01, 2.12666700e-01],
       [1.03484771e-01, 8.96515229e-01],
       [3.47153061e-06, 9.99996528e-01],
       [9.84946204e-01, 1.50537965e-02],
       [8.40802760e-01, 1.59197240e-01],
       [9.83669510e-04, 9.99016330e-01],
       [3.193022

In [ ]:
data=[[1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1]]
ypredic = nbtrain.predict(data)
print(ypredic)

[1]


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 61,  90],
       [145, 204]])